steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '-b', 'prod', '--single-branch', 'https://github.com/soulforger0/simple_linear_train', 'app']
#- name: 'python:3.8-slim-buster'
#  entrypoint: 'python'
#  args: ['-m', 'pip', 'install', '-r', 'app/requirements.txt']
#- name: 'python:3.8-slim-buster'
#  entrypoint: 'python'
#  args: ['app/training_data_pipe.py']
#- name: 'gcr.io/cloud-builders/gsutil'
#  args: ['cp', '-r', './prod_model', 'gs://prod_model/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-linear-trainpipe', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/simple-linear-trainpipe']
images:
- 'gcr.io/$PROJECT_ID/simple-linear-trainpipe'