steps:
#- name: 'gcr.io/cloud-builders/git'
#  args: ['clone', '-b', 'prod', '--single-branch', 'https://github.com/soulforger0/simple_linear_train', 'app']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-linear-trainpipe', '.']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/$PROJECT_ID/simple-linear-trainpipe']

#- name: 'gcr.io/cloud-builders/docker'
#  args: [
#    'run',
#    '--rm',
#    'gcr.io/$PROJECT_ID/simple-linear-trainpipe',
#    'pytest',
#    'app/unit_test_trainpipe.py'
#  ]

- name: 'gcr.io/cloud-builders/docker'
  volumes:
    - name: 'prod_model'
      path: '/app/prod_model'
  args: [
    'run',
    '--rm',
    'gcr.io/$PROJECT_ID/simple-linear-trainpipe',
    'bash',
    '-c',
    #'python3 app/training_data_pipe.py && gsutil -m rsync -r -d app/prod_model gs://prod_model/'
    'python3 app/training_data_pipe.py'
  ]
#artifacts:
#  objects:
#    location: 'gs://prod_model/'
#    paths: ['./prod_model/*.pickle']
    
- name: gcr.io/cloud-builders/gsutil
  volumes:
    - name: 'prod_model'
      path: '/app/prod_model'
  args: ['rsync', "-r", "-d", 'app/prod_model/', 'gs://prod_model']
