steps:
#- name: 'gcr.io/cloud-builders/git'
#  args: ['clone', '-b', 'prod', '--single-branch', 'https://github.com/soulforger0/simple_linear_train', 'app']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-linear-trainpipe', '.']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/$PROJECT_ID/simple-linear-trainpipe']

#- name: 'gcr.io/cloud-builders/docker'
#  args: [
#    'run',
#    '--rm',
#    'gcr.io/$PROJECT_ID/simple-linear-trainpipe',
#    'pytest',
#    'app/unit_test_trainpipe.py'
#  ]


- name: 'gcr.io/cloud-builders/docker'
  id: 'train_model'
  args: [
    'run',
    '--rm',
    'gcr.io/$PROJECT_ID/simple-linear-trainpipe',
    'bash',
    '-c',
#    #'python3 app/training_data_pipe.py && gsutil -m rsync -r -d app/prod_model gs://prod_model/'
    'python3 app/training_data_pipe.py'
  ]
#artifacts:
#  objects:
#    location: 'gs://prod_model'
#    paths: ['./prod_model/*.pickle']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'app/prod_model/*.pickle', 'gs://prod_model']
  
#- name: 'gcr.io/$PROJECT_ID/simple-linear-trainpipe'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#  - python3 app/training_data_pipe.py &&
#  - cp app/prod_model/*.pickle /workspace/model_to_serve
  #- rsync -a app/prod_model/ /workspace/model_to_serve
 
    
#- name: gcr.io/cloud-builders/gsutil
#  args: ['rsync', "-r", "-d", '/workspace/model_to_serve', 'gs://prod_model']
